### ISSUE TITLE
Está comunidade está oficialmente morta?

### ISSUE THREAD

**Issue by JoseCage** [AngoDev/PortalAngoDev#18]
Boas pessoal.  Como todos podem notar, a comunidade nos últimos tempos tem estado muito off o que me leva a questão "ESTÁ COMUNIDADE NÃO VOLTA A ATIVA?"

**Comment by firminochangani** [comment]
@JoseCage Boa questão. Mas para não ficar só no mimi, uma solução que pretendo ir implementando são pequenos meetups de 5 a 10 pessoas. A ideia é que qualquer possa pegar no modelo do meetup e reproduzir na sua localidade, bairro, escola, em fim. Um exemplo é um FEMUG no Brasil.

**Comment by JoseCage** [comment]
Certo @flowck....
Seria uma boa a questão de expandir.. No entanto, quanto a @AngoDev/developers propriamente??

**Comment by psantos10** [comment]
@JoseCage AngoDev como comunidade depende de pessoas (programadores) para que exista. Não pertence a uma pessoa apenas, mas sim a comunidade como um todo. E sendo assim, é a comunidade quem deve dar vida ao projecto e não uma pessoa apenas. 

Por mim, sim... a comunidade está morta. Aliás, nunca existiu. Talvez numa próxima geração apareça alguém para dar vida ao mesmo. NEsta que eu conheço, duvido muito. Contudo, espero que eu esteja errado.

Abs

**Comment by JoseCage** [comment]
@psantos10 Sei que uma comunidade é formada de várias pessoas. Mas de qualquer das formas há sempre entre essas pessoas alguém que esteja digamos na frente, referente a gestão da mesma comunidade.. :octocat:

**Comment by firminochangani** [comment]
@JoseCage Pelo que tenho visto, lá fora não há um gestor ou algo centralizado, mas sim vários grupos que realizam actividades formando então a comunidade.

**Comment by JoseCage** [comment]
Era sim suposto aqui ser assim @flowck 

A questão é que ao certo não se sabe o que falta-nos para tal. Em tempos (propriamente com o Meet.Us) via-se que as coisas ganhavam um ritmo. Que depois acabou por paralisar..
